details:
  - analysis: variant2
    genome_build: hg38
    algorithm:
      # Alignment parameters
      aligner: bwa
      recalibrate: false
      realign: false
      mark_duplicates: true
      remove_lcr: false

      # Poly-G filtering
      trim_reads: atropos
      adapters: polyx

      # QC and coverage assessent
      coverage: /g/data/pq08/example_scripts/bcbio/umccr_specific_files/umccr_cancer_genes.hg38.transcript.bed

      # Variant calling, strelka2 only
      variantcaller:
        germline: [strelka2]
        somatic: [strelka2] 

      # Call down to 1% allelic frequency
      min_allele_fraction: 1

      # Exclude difficult regions
      variant_regions: /g/data/pq08/example_scripts/bcbio/umccr_specific_files/hg38_noalt_noBlacklist.bed
      exclude_regions: [altcontigs]

      # Structural variation. No ensemble calling option here
      svcaller: [manta]
#      svprioritize: umccr_cancer_genes.latest.genes

      # Add HLA
#      hlacaller: optitype

      # Extras
      tools_on: [break-point-inspector]
      tools_off: [contamination]
      save_diskspace: true
     
upload:
  dir: ../final
resources:
  manta:
    options:
    - --generateEvidenceBam 
    - --outputContig
