---
title: "A5 GRIDSS-Manta SV filtering"
author: "Aidan Flynn"
date: "03/06/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Dependencies
```{r source_dependencies, message=FALSE, warning=FALSE}
source("C:/Users/AFFLY/OneDrive - The University of Melbourne/ResearchData/RADIO/utility/compare_vcf_calls.r")
library(ggplot2)


```
``` {r sample_list}
#List of A5 patients with paired samples
Samples <- list(
  E122=c("E122-T01","E122-T02"),
  E128=c("E128-T01","E128-T02"),
  E132=c("E132-T01","E132-T02"),
  E143=c("E143-T01","E143-T02","E143-T03"),
  E146=c("E146-T01","E146-T02"),
  E158=c("E158-T01","E158-T02"),
  E159=c("E159-T01","E159-T02","E159-T03","E159-T04"),
  E166=c("E166-T01","E166-T02"),
  E167=c("E167-T01","E167-T02"),
  E169=c("E169-T01","E169-T02"),
  E225=c("E225-T01","E225-T02"),
  E229=c("E229-T01","E229-T02")
)
```
```{r run_comparisions}
gridss_manta_comps_all <- list()
gridss_manta_comps_hq <- list()
for (patient in names(Samples))
{
  for (s in Samples[[patient]])
  {
    gridss_vcf <-
      readVcf(
        paste0(
          "C:/ResearchData/RADIO/A5/Data/WGS/hg38/sv/gridss/purple/",
          s,
          ".purple.sv.vcf.gz"
        )
      )
    
    gridss_vcf <- gridss_vcf[filt(gridss_vcf) == "PASS", ]
    RP <- geno(gridss_vcf)[["RP"]][, which(colnames(gridss_vcf) == s)]
    SR <- geno(gridss_vcf)[["SR"]][, which(colnames(gridss_vcf) == s)]
    keep_gridss_vcf <- (RP > 7 | SR > 7 |  (RP > 4 & SR > 4))
    keep_gridss_vcf[is.na(keep_gridss_vcf)] <- FALSE
    gridss_vcf.hq <- gridss_vcf[keep_gridss_vcf]
    
    manta_vcf <-
      readVcf(
        paste0(
          "C:/ResearchData/RADIO/A5/Data/WGS/hg38/sv/manta/purple/",
          gsub("T0", "", s),
          "__",
          s,
          ".purple.sv.vcf.gz"
        )
      )
    
    manta_vcf <- manta_vcf[filt(manta_vcf) == "PASS", ]
    
    PR_available <- lapply(geno(manta_vcf)[["PR"]][, which(colnames(manta_vcf) == s)], length) == 2
    SR_available <- lapply(geno(manta_vcf)[["SR"]][, which(colnames(manta_vcf) == s)], length) == 2
    manta_vcf.hq <- manta_vcf[PR_available & SR_available, ]
    
    PR <- sapply(geno(manta_vcf.hq)[["PR"]][, which(colnames(manta_vcf.hq) == s)], "[[", 2)
    SR <- sapply(geno(manta_vcf.hq)[["SR"]][, which(colnames(manta_vcf.hq) == s)], "[[", 2)
    
    keep_manta_vcf.hq <- PR > 7 | SR > 7 | (PR > 4 & SR > 4)
    
    keep_manta_vcf.hq[is.na(keep_manta_vcf.hq)] <- FALSE
    
    manta_vcf.hq <- manta_vcf.hq[keep_manta_vcf.hq]
    
    gridss_manta_comps_all[[s]] <-
      compare_sv_vcfs(
        vcf1 = gridss_vcf,
        vcf2 = manta_vcf,
        normal_name_vcf1 =  gsub("T0.", "B01", s),
        tumour_name_vcf1 = s,
        tumour_name_vcf1_override = paste0(s, "_gridss"),
        normal_name_vcf2 = NULL,
        tumour_name_vcf2 = s,
        tumour_name_vcf2_override = paste0(s, "_manta"),
        genome = "BSgenome.Hsapiens.UCSC.hg38",
        maxgap = 0,
        sizemargin = 0
      )
    
    gridss_manta_comps_hq[[s]] <-
      compare_sv_vcfs(
        vcf1 = gridss_vcf.hq,
        vcf2 = manta_vcf.hq,
        normal_name_vcf1 =  gsub("T0.", "B01", s),
        tumour_name_vcf1 = s,
        tumour_name_vcf1_override = paste0(s, "_gridss"),
        normal_name_vcf2 = NULL,
        tumour_name_vcf2 = s,
        tumour_name_vcf2_override = paste0(s, "_manta"),
        genome = "BSgenome.Hsapiens.UCSC.hg38",
        maxgap = 0,
        sizemargin = 0
      )
  }
  
}
```
## Summarise matched SVs to counts
```{r summarise_counts}

gridss_manta_called <- list()
for (patient in names(Samples))
{
  for (s in Samples[[patient]])
  {
    gridss_manta_called[[s]] <-
      #unfiltered data
      gridss_manta_comps_all[[s]] %>% 
      filter(!grepl("o$|bp1$|:0$", partner)) %>% #remove duplicated partner entries
      group_by(across(matches("_Called"))) %>% 
      count() %>% 
      ungroup() %>%
      mutate(source = "All") %>%  
      bind_rows(
        #Filtered data
        gridss_manta_comps_hq[[s]] %>% 
          filter(!grepl("o$|bp1$|:0$", partner)) %>%  
          group_by(across(matches("_Called"))) %>% 
          count() %>% 
          ungroup() %>% 
          mutate(source ="Filter")
      ) %>%
      #replace TRUE with column name and FALSE with NA
      mutate(across(
        .cols = matches("_Called"),
        .fns = ~ ifelse(.x, gsub(".+_(.+)_.+", "\\1", cur_column()), NA_character_)
      )) %>%
      unite(
        col = "Called",
        matches("_Called"),
        sep = "/",
        na.rm = T
      ) %>%
      mutate(Sample = s)
  }
}
gridss_manta_called.summary <- bind_rows(gridss_manta_called)
```
## Diagnostic Plots
```{r summary_plots}
ggplot(gridss_manta_called.summary, aes(y=n,x=Sample, fill=Called)) + geom_col() + theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1)) + 
  facet_wrap("source", nrow=2, scale="free_y", labeller = function(input) { data.frame(All=c("All SVs","Filtered: (PR > 7 or SR > 7 or  (PR > 4 and SR > 4))")) })

gridss_manta_called.summary %>%  filter(Called=="gridss/manta") %>%  pivot_wider(id_cols = c(Sample,Called), names_from = source, values_from=n) %>% 
  ggplot(aes(x=All, y=Filter)) + geom_point() + geom_abline(slope=1, intercept = 0) + theme(aspect.ratio = 1)
```